# Generated by Django 3.2.11 on 2022-01-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug_title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('publish_on', models.DateTimeField(blank=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
