# Generated by Django 3.2.11 on 2022-01-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_publish_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug_title',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
