# Generated by Django 3.2.11 on 2022-01-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_auto_20210216_2348'),
        ('blog', '0004_emailorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailorder',
            name='flags',
            field=models.ManyToManyField(related_name='emailorders', to='members.MemberFlag'),
        ),
    ]
