# Generated by Django 3.0.3 on 2020-02-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranks',
            new_name='Rank',
        ),
    ]
