# Generated by Django 3.0.3 on 2020-02-26 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200226_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
