# Generated by Django 3.0.3 on 2020-02-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200227_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='member',
            field=models.ManyToManyField(related_name='ranks', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_name',
            field=models.CharField(choices=[('SUSPENDED', 'Suspended'), ('EXPELLED', 'Expelled'), ('GATEKEEPER', 'Gatekeeper'), ('WEBKEEPER', 'Webkeeper'), ('COMMITTEE', 'Committee'), ('LIFEMEMBER', 'Life Member')], max_length=20),
        ),
    ]
