# Generated by Django 3.0.3 on 2020-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200227_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='preferred_name',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
