# Generated by Django 3.0.3 on 2020-02-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200227_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
