# Generated by Django 3.0.3 on 2020-02-27 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200227_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
