# Generated by Django 3.0.3 on 2020-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20200227_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pronouns',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
