# Generated by Django 3.0.3 on 2020-02-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(choices=[('MAIL', 'Mailing List'), ('FRESHERCAMPAIGN', 'Fresher Campaign'), ('WARGAMING', 'Wargaming'), ('MAGIC', 'Magic')], max_length=20)),
                ('member', models.ManyToManyField(related_name='interests', to='members.Member')),
            ],
        ),
    ]
