# Generated by Django 3.1 on 2020-08-09 08:28

from django.db import migrations


def add_ranks(apps, schema_editor):
    Rank = apps.get_model('members', 'Rank')
    RankChoices = Rank._meta.get_field('rank_name').choices

    for choice in RankChoices:
        r = Rank(rank_name=choice[0])
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20200808_0502'),
    ]

    operations = [
        migrations.RunPython(add_ranks)
    ]
