# Generated by Django 3.1 on 2020-08-28 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20200809_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(auto_now_add=True)),
                ('rank_expired', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.rank')),
            ],
        ),
        migrations.RemoveField(
            model_name="rank",
            name='member',
        ),
        migrations.AddField(
            model_name='rank',
            name='member',
            field=models.ManyToManyField(related_name='ranks', through='members.RankAssignments', to='members.Member'),
        ),
    ]
