# Generated by Django 3.1.4 on 2020-12-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20201220_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('member', models.ManyToManyField(related_name='flags', to='members.Member')),
            ],
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
