# Generated by Django 3.1.4 on 2020-12-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20201230_0816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberFlags',
            new_name='MemberFlag',
        ),
    ]
