# Generated by Django 3.1.4 on 2020-12-30 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20201230_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]+$')]),
        ),
    ]
