# Generated by Django 3.1.4 on 2020-12-31 07:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20201230_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='member',
            name='receive_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='amount_paid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='authorising_gatekeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatekeeper', to='members.member'),
        ),
        migrations.AddField(
            model_name='membership',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='members.member'),
        ),
    ]
