# Generated by Django 3.1.4 on 2021-01-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20201231_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='authorising_gatekeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised', to='members.member'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member'),
        ),
    ]
