# Generated by Django 3.1.4 on 2021-01-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20210101_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
