# Generated by Django 3.1.4 on 2021-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20210105_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
