# Generated by Django 3.1.4 on 2021-02-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20210208_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='auth_gatekeeper_name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
