# Generated by Django 3.1.4 on 2021-02-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_membership_auth_gatekeeper_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
