# Generated by Django 3.1.4 on 2021-02-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_auto_20210212_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='authorising_gatekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised', to='members.member'),
        ),
    ]
