# Generated by Django 3.1.4 on 2021-02-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_auto_20210215_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='member',
            field=models.ManyToManyField(through='members.RankAssignments', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='rankassignments',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='members.member'),
        ),
        migrations.AlterField(
            model_name='rankassignments',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='members.rank'),
        ),
    ]
