# Generated by Django 3.2.20 on 2023-10-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_auto_20210216_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['preferred_name', 'last_name']},
        ),
    ]
